Eppo-exp/eppo-docs

docs/interpreting-experiments/cuped.md

Thanks Ren for creating these docs! Made a few edits

CUPED edits

---

docs/feature-flagging/randomization-sdk.md

Updated from instructions here:
https://www.notion.so/eppo/Client-SDK-Documentation-Updates-2da8f0e4508f491f907bdbde93da6053

Update randomization sdk docs

---

docs/building-experiments/metrics/creating-metrics.md

* Descriptions of each type of aggregation
* Removed reference to metric-based filters (no longer exist)
* Minor rewordings

Improvements to metrics docs

---

docs/building-experiments/metrics/creating-metrics.md

This reverts commit 06d6ccc9a2addd41b819e1e195a69cc575cf8510.

Revert "Improvements to metrics docs (#26)"

---

docs/interpreting-experiments/index.md

Add description of segments and filters

Add segments and filters to interpreting experiments

---

docusaurus.config.js

Updated Algolia Search API keys.

opened new branch and updated search API keys

---

docs/quickstart.md

@megan-eppo Please let me know if this looks alright. Not sure how to resize the image, if possible, we should have the map a bit small but it can be clicked to view the full image.

Added a relationship map

---

docs/prerequisites/feature-flagging/index.md
docs/prerequisites/index.md

Typo and a little wordsmithing on the Prerequisites page.

a few small edits

---

docs/prerequisites/feature-flagging/randomization-sdk/server-sdks/java.md

Added documentation for JAVA sdk

Adding JAVA sdk doc

---

docs/Administration/slack-notifications.md
docs/administration/_category_.json

add category.json to administration

add category.json

---

docusaurus.config.js

Link "edit this page" to this repo

Fix "Edit this page" link

---

docs/experiments/interpreting-experiments/confidence-intervals.md

Update the docs to add covariance term in delta method for ratio metric.

[CI/ratio-metrics] add covariance term

---

docs/administration/slack-notifications.md
yarn.lock

deploy was broken https://app.netlify.com/sites/adoring-yonath-6ecb9d/deploys/63c981b4e614d4000800ff28
```
9:47:20 AM: SyntaxError: /opt/build/repo/docs/administration/slack-notifications.md: Unexpected token (9:3)
9:47:20 AM:    7 |
9:47:20 AM:    8 | <h1 {...{"id":"slack-notifications"}}>{`Slack notifications`}</h1>
9:47:20 AM: >  9 | <p "float: left">
9:47:20 AM:      |    ^
```

fix p tag in slack notifications

---

docs/experiments/connecting-your-data/data-warehouses/connecting-to-redshift.md

We have a programmatic way to connect customers via AWS IAM but no UI is built at this time. Are you ok with this language?

add docs about redshift iam (ANA-49)

---

docs/feature-flags/sdks/server-sdks/index.md
docs/feature-flags/sdks/server-sdks/php.md

Adds documentation for new php-sdk (https://github.com/Eppo-exp/php-sdk/)
Currently waiting for this PR to be merged:
https://github.com/Eppo-exp/php-sdk/pull/1/files

ANA-182 add php-sdk documentation

---

docs/experiments/building-experiments/experiments/creating-experiments.md

Add a paragraph about the new filter by entry point feature.

Filter assignments by entry point

---

docs/experiments/interpreting-experiments/index.md

Fix Probability > Precision in docs

---

docs/feature-flags/sdks/client-sdks/android.md
docs/feature-flags/sdks/client-sdks/ios.md
docs/feature-flags/sdks/client-sdks/javascript.md
docs/feature-flags/sdks/server-sdks/go.md
docs/feature-flags/sdks/server-sdks/java.md
docs/feature-flags/sdks/server-sdks/node.md
docs/feature-flags/sdks/server-sdks/php.md
docs/feature-flags/sdks/server-sdks/python.md
docs/feature-flags/sdks/server-sdks/ruby.md

Updating FF change propagation to reflect Fastly CDN

update 5 minutes to 10 seconds in FF docs

---

docs/data-management/metrics/simple-metric.md

I feel like adding some pseudo-code may help make our logic of computing metrics a bit clearer to some. Open to feedback on whether this is indeed helpful

Add SQL pseudo-code to simple-metric page

---

docs/statistics/confidence-intervals/analysis-methods.md

Small tweak to the wording of a run-on sentence.

Update wording on sample size calculation for seq analysis

---

docs/feature-flags/sdks/android.md
docs/feature-flags/sdks/dotnet.md
docs/feature-flags/sdks/go.md
docs/feature-flags/sdks/ios.md
docs/feature-flags/sdks/java.md

* updates to latest version
* example usage

dynamic configuration (FF-804)

---

docs/feature-flags/sdks/index.md

document assignment logging deduplication (FF-1073)

---

docs/feature-flags/sdks/ruby.md

Reported issue with our docs: https://github.com/Eppo-exp/ruby-sdk/issues/7

Remove python line in ruby doc

---

docs/how-tos/non-inferiority-tests.md

Small updates to the non-inferiority test guide

Small updates to the non-inferiority test guide

---

docs/how-tos/running-well-powered-experiments.md

adding how to doc on running well powered experiments in low sample size scenarios

low sample size how to

---

docs/quick-starts/setup-quickstart.md

Quick Fix: feilds instead of fields typo

---

docs/experiment-analysis/index.md

[Reported](https://eppo-group.slack.com/archives/C058QMZ6XQC/p1707762944452689) by @ryanlucht

Fix broken image in experiment-analysis index

---

docs/experiment-analysis/progress-bar.md

Fix inconsistency in progress bar page for fixed sample methodology

Progress bar for fixed sample fix

---

docs/data-management/metrics/funnel-metric.md

Following this conversation:
https://eppo-group.slack.com/archives/C066DUW0020/p1708607983677339

Clarifying that funnel metric need to be NULL not zero

---

docs/statistics/confidence-intervals/statistical-nitty-gritty.md

Fix bound term for sequential test

---

docs/guides/anonymous-explainer.md

The cumulative total only works if the window function is UNBOUNDED PRECEDING, not overall.
Plus consistency in the SQL code: space indentation, capitalized keywords, initial commas.

Fix cumulative window function status change

---

docs/sdks/server-sdks/node.md

Small nit: should we drop the initialization and get assignment calls in the section on logging to make it a bit clearer what each line is doing? 
Also, a few small things that Grammarly caught :)
Huge improvement though!

minor edits to node docs

---

docs/experiment-analysis/best-practices.md
docs/experiment-analysis/data-pipeline.md

Small change after this conversation https://eppo-group.slack.com/archives/C01TTTNMCBB/p1711645153704349

Remind that multiple exposure leads to exclusion

---

docs/data-management/metrics/simple-metric.md
docs/experiment-analysis/filter-assignments-by-entry-point.md

Small PR after a client’s question.
SQL details [here](https://eppo-group.slack.com/archives/C04QJSSS0H5/p1712671428011969?thread_ts=1712669125.888229&cid=C04QJSSS0H5).

Clarify how entry point and time-framed metrics work

---

docs/data-management/metrics/certified-metrics.md

Client flagged it
https://eppo-group.slack.com/archives/C03K06LU1L5/p1713870623538059?thread_ts=1713865592.357029&cid=C03K06LU1L5

Certified metrics had a bug

---

docs/data-management/definitions/fact-sql.md
docs/data-management/metrics/simple-metric.md
docs/experiment-analysis/diagnostics.md
docs/feature-flagging/audit-log.md

* Partition keys
* Aged conversion metrics
* Mixed assignment diagnostic
* Removed beta label from restore flag version

Updated docs for new features

---

docs/administration/authentication.md
docs/experiment-analysis/creating-experiments.md

./okta -> /administration/okta

Fixing more relative path links

---

docs/sdks/server-sdks/java.md
docs/sdks/server-sdks/python.md

Adding documentation on how to use Contextual bandits with the Python SDK

Contextual bandit docs for Python SDK

---

docs/data-management/definitions/fact-sql.md

Added a note clarifying which column to use for fact values

Added a note about how the fact column should be numeric or string

---

docs/guides/optimizely-migration.md
docs/quick-starts/experiment-allocation-quickstart.md
docs/quick-starts/feature-flag-quickstart.md
docs/sdks/client-sdks/android.md
docs/sdks/client-sdks/javascript.md
docs/sdks/client-sdks/react-native.md
docs/sdks/common-issues.md
docs/sdks/sdk-features/flag-types.md
docs/sdks/server-sdks/node.md

Reflect incoming changes to @eppo/js-client-sdk v3.1.0 in https://github.com/Eppo-exp/js-client-sdk/pull/77

chore(js): Update js docs to reflect new API

---

docs/reference/integrations/index.md

Changed "blue" to "purple" to represent what is actually in the table

Fix third party integrations variation typo.md

---

docs/statistics/cuped.md

- Fixed typo in CUPED info box
- Added links to the relevant feature pages for which we do not calculate CUPED estimates
- Re-wrote info box to be more concise to improve readability

Update CUPED caution copy.md

---

docs/sdks/server-sdks/python.md

Update the docs to incorporate the recent change from list to dict

[ff-2388] Python bandit docs: action list -> dict

---

docs/guides/engineering/nextjs-setup.md

Updated the SSR documentation with a more-straightforward approach. Some of the changes were automatic by VS Code, but it shouldn't hurt anything.

Update eppo guide for Next.js SSR integration

---

docs/guides/engineering/nextjs-setup.md

Looks like I left in part of the old documentation 😬

remove deprecated section for server rendering

---

docs/data-management/certified-metrics/certified-metrics.md
docs/data-management/certified-metrics/dbt-models.md

[Flagged](https://eppo-group.slack.com/archives/C058QMZ6XQC/p1718661600345519) by Rachel. I did a global search and replace: `DBT` -> `dbt`.

Replace DBT with dbt globally

---

docs/sdks/client-sdks/android.md
docs/sdks/server-sdks/java.md

fix: Bump SDK versions for Android and JVM

---

docs/data-management/metrics/simple-metric.md

Add notes on HyperLogLog (including the fact that Redshift only supports it):

Add hyperloglog to Count Distinct section.

---

docs/sdks/sdk-features/debugging-flag-assignment.md

Looks like I made a copy-paste mistake on my last update to this documentation

fix docs for debugging-flag-assignment

---

docs/guides/advanced-experimentation/entry_points.md

Fix broken link

---

docs/sdks/client-sdks/android.md

Reverting (and updating to the latest version) per [feedback](https://github.com/Eppo-exp/eppo-docs/pull/434#discussion_r1697256623).

Point to latest Android SDK version

---

docs/data-management/definitions/assignment-sql.md

I checked that this was the case [looking at recent updates](https://eppo-group.slack.com/archives/C066DUW0020/p1725350144277189?thread_ts=1724813725.656619&cid=C066DUW0020).

Clarifying Assignment edits

---

docs/guides/engineering/nextjs-setup.md

Updated documentation for Next.js SSR tutorial to support the legacy "Pages Router". A developer from RS Group said that it would be helpful for them to integrate Eppo into their codebase.

Add "Next.js Pages Router" support for Next.js SSR tutorial

---

docs/guides/migrations/launchdarily-migration.md

A table would be easier to understand.

Replacing link to Google Docs to a table

---

docs/statistics/confidence-intervals/index.md

Some clients have been asking why certain results to not appear. This note in the docs will help point them at an official explanation.

Clarifying when we do not compute the relative lift

---

docs/guides/migrations/launchdarily-migration.md

Explicitly listing the variants that the developper will have to consider when transitioning.

Clarifying LaunchDarkly migration guide

---

docs/guides/migrations/launchdarily-migration.md

@felipecsl found a typo in the previous push

LaunchDarkly Migration, Clarifications

---

docs/data-management/metrics/simple-metric.md

Just the public docs for `Last Value`.

Last value docs

---

docs/experiment-analysis/deep-dive/segments.md

This publishes [this comment by Sven](https://eppo-group.slack.com/archives/C066DUW0020/p1726070498719999?thread_ts=1726064038.415289&cid=C066DUW0020).
[Here’s the line of code that does that filters them out](https://github.com/Eppo-exp/eppo/blob/c9e2c5074917c2291e6fe9475bf4f87e0ad4ee5e/packages/api/src/console/db-aggregations/experiment-dimensionalized-summaries-reduced.blocks.spec.ts#L91).

Spell out that Segments have to have five subjects for privacy

---

docs/data-management/certified-metrics/upgrading-metrics.md

effected -> affected
@lukasgoetzweiss

Fix small typo in upgrading-metrics.md

---

docs/data-management/connecting-dwh/redshift.md

We don't support IAM at the moment. Most of the code is written but it requires an additional few days of development.

Remove redshift IAM section

---

docs/sdks/server-sdks/python/_category.json
docs/sdks/server-sdks/python/announcing-python-4-0.md
docs/sdks/server-sdks/python/index.md

To be merged after https://github.com/Eppo-exp/rust-sdk/pull/29

FF-2945 Add announcement for Python SDK 4.0

---

docs/feature-flagging/concepts/mutual_exclusion.md

Publishing Heather's edits to layers

Updating layers docs

---

docs/data-management/certified-metrics/eppo-schema.md

Our metric sync package has been updated [here](https://github.com/Eppo-exp/eppo-metrics-sync/pull/11) but not our documentation.

Update to new aggregation_timeframe_value fields

---

docs/sdks/client-sdks/android.md

""never a chore to update the docs" - Wayne Gretzky" - Tyler Potter

chore:Update docs for Android SDK

---

src/css/custom.css

undoing some changes that my original css PR cobbled

fixed css issues

---

docs/sdks/server-sdks/go.md

* Latest release is `v6`
* New blocking initialization functionality added
Preview of changes: https://deploy-preview-498--eppo-data-docs.netlify.app/sdks/server-sdks/go/

golang bump to v6; adds initialization instructions

---

docs/data-management/data-pipeline.md

Adds more detailed information on how metric dimensions are computed.

Add how top metric dimension values determined.

---

docs/sdks/faqs/latency.md

Added results from Eric's latency benchmark

updated latency page

---

docs/data-management/certified-metrics/dbt-models.md
docs/data-management/certified-metrics/eppo-schema.md

Update the GH action examples to install v0.0.4 of the eppo-metrics-sync package

updated github action examples to use recent package version

---

static/_redirects

adding redirects for old faq articles

---

docs/sdks/server-sdks/python/assignments.mdx
docs/sdks/server-sdks/python/bandits.mdx
docs/sdks/server-sdks/python/initialization.mdx
docs/sdks/server-sdks/python/quickstart.mdx

Review python docs

---

docs/sdks/preforking.md

Add Puma, Unicorn and Phusion Passenger to Ruby SDK preforking init instructions

chore(ruby): Add preforking instructions for more frameworks

---

docs/sdks/server-sdks/php/assignments.mdx
docs/sdks/server-sdks/php/bandits.mdx
docs/sdks/server-sdks/php/initialization.mdx
docs/sdks/server-sdks/php/quickstart.mdx

docs: additional PHP examples

---

docs/sdks/server-sdks/dotnet/assignments.mdx
docs/sdks/server-sdks/dotnet/bandits.mdx
docs/sdks/server-sdks/dotnet/initialization.mdx

docs: tweaks to the dotnet docs

---

docs/sdks/client-sdks/android/initialization.mdx

feat: Add docs for android polling

---

docs/sdks/index.md
docs/sdks/server-sdks/index.md
docusaurus.config.js
package.json
yarn.lock

Added Google Analytics Docusaurus plugin and updated config file to include tracking settings per request from Marketing team.

feat: Add Google Analytics tracking plugin for improved analytics

---

docusaurus.config.js
package.json
yarn.lock

Add Microsoft Clarity for visitor session recording per marketing request

feat: Add Microsoft Clarity for visitor session recording

---

docs/feature-flagging/concepts/targeting.md

Add a note on formatting for SemVer versioning

Targeting: add a note on semver

---

docs/statistics/confidence-intervals/index.md
docs/statistics/sample-size-calculator/usage.md

Update the docs to reflect our changes to using the normal approximation for ratio metrics

Add Kuethe's criterion for validity of ratio metrics to docs

---

docs/sdks/server-sdks/java/assignments.mdx
docs/sdks/server-sdks/java/bandits.mdx
docs/sdks/server-sdks/java/initialization.mdx
docs/sdks/server-sdks/java/quickstart.mdx

docs: java docs suggestions

---

docs/sdks/server-sdks/java/bandits.mdx
docs/sdks/server-sdks/java/initialization.mdx
docs/sdks/server-sdks/java/quickstart.mdx

Fixes FF-4061
Breaking changes in [java-server#104](https://github.com/Eppo-exp/java-server-sdk/pull/104) and [105](https://github.com/Eppo-exp/java-server-sdk/pull/105)

chore:Update java docs for v5 release

---

docusaurus.config.js

Addition of new announcement bar to promote upcoming live demos

feat: add announcement bar for upcoming live demos

---

docusaurus.config.js
src/css/custom.css

addition of login and sign up buttons to the navbar

feat: add login and sign up buttons to the navbar

---

docs/geolift/geolift-data.md

add new geolift data model page

add new geolift data model page

---

docs/sdks/client-sdks/ios/initialization.mdx

To describe the changes in https://github.com/Eppo-exp/eppo-ios-sdk/pull/58

Configuration export in iOS

---

docs/sdks/client-sdks/ios/initialization.mdx

Related PR https://github.com/Eppo-exp/eppo-ios-sdk/pull/60

Polling in iOS

---

docs/reference/webhook.mdx

chore: user_email in webhook for flag updates

---

docs/data-management/connecting-dwh/bigquery.md

A client asked about this permission, finding it excessive.

Remove warehouse requirements for Event Logging
