docs/feature-flagging/randomization-sdk.md
Changes:
- The python `assign` function is renamed to `get_assignment`
- The Node `init` method is changed from sync to async
- A `getInstance()` util function was added to the Node SDK for retrieving the singleton client instance. (the python SDK already has this method).
=> Update code examples to align with v1.0 SDK

docs/feature-flagging/randomization-sdk/client-sdks/javascript.md
Some consumers might want to install the frontend SDK via a `<script>` tag. This is possible by loading the SDK from JSDelivr - an open source CDN that distributes the minified SDK source. I added documentation for how to install it.
Related PR for setting up webpack and JSDelivr: https://github.com/Eppo-exp/js-client-sdk/pull/5
=> Include instructions for installing via script tag

docs/connecting-your-data/data-warehouses/connecting-to-bigquery.md
The doc for configuring BQ doesn't have the same description of what to use for each field that we have for SF and Redshift. This just adds a short description of what to use for each field.
Motivated by some friction that Origin had setting up their connection
=> Added more details to BQ configuration

docusaurus.config.js
Dark mode currently doesn't look good; especially with the purple links that become illegible. Turn off until we can find a theme that works.
=> Disable dark mode

docs/prerequisites/feature-flagging/index.md, docs/prerequisites/index.md
The links on the prerequisites page were broken - should end with a slash '/' when it links to a directory
=> Fix broken links

docs/connecting-your-data/data-warehouses/connecting-to-redshift.md
Instawork noticed that we are missing the schema name in part of our connecting redshift docs
=> fixed missing schema name typo

docs/administration/slack-notifications.md
There was unterminated `<img>` tag that was blowing up compilation. This was caused by a commit from the Github UI.
=> get main to compile

docs/experiments/interpreting-experiments/experiment-progress-bar.md
Currently blue is determined by currently detectable effect, not statistical significance
=> Blue progress bar explanation fix

docs/feature-flags/sdks/server-sdks/python.md, docs/quick-starts/your-first-experiment-analysis.md
New diagram contains our updated logo:
=> [logo] update eppo relationship map with new logo on experiment quickstart

docs/feature-flags/sdks/server-sdks/index.md, docusaurus.config.js
I just realized that the syntax highlighting was broken, but it looks like an easy fix. I tested this out locally and confirmed that it works
Before
After
=> Fix Ruby syntax highlighting

docs/experiments/prerequisites/event-logging/index.md, docs/feature-flags/sdks/client-sdks/android.md, docs/feature-flags/sdks/client-sdks/javascript.md, docs/feature-flags/sdks/server-sdks/go.md, docs/feature-flags/sdks/server-sdks/java.md, docs/feature-flags/sdks/server-sdks/node.md, docs/feature-flags/sdks/server-sdks/python.md, docs/feature-flags/sdks/server-sdks/ruby.md
[EPD-946](https://linear.app/eppo/issue/EPD-946/[docs]-more-event-logging-configuration-examples)
Added examples as captured on Linear, although I can't guarantee that all of these work exactly as advertised. mParticle and Snowplow, in particular, have more complicated SDKs and I didn't personally try them out myself.
Also, I included links to the event-logging page on each SDK page EXCEPT for iOS because I didn't see anything in the docs about assignment logging and was not sure if it was supported by the iOS SDK.
=> EPD-946 [Docs] More event logging configuration examples

docs/feature-flags/sdks/server-sdks/java.md
this was surfaced in the Inventa POC where the used the listed (deprecated) version which called our deprecated API endpoint. updating the docs here to be current.
https://eppo-group.slack.com/archives/C04EXAWHFRA/p1675363766135449
=> update java sdk version listed from 1.0.2 => 1.1.0

docs/administration/slack-notifications.md
Adding a short opening paragraph, primarily so that the Slack preview doesn't look borked
=> Slack notifications: add a opening paragraph

docs/feature-flags/sdks/client-sdks/android.md, docs/feature-flags/sdks/client-sdks/ios.md, docs/feature-flags/sdks/client-sdks/javascript.md
`Randomization` was renamed to `Feature Flagging` in the app but not here in the docs. Updating!
=> update copy in docs to reflect api permission modal

static/_redirects
**previously eppo's netlify docs page was being indexed by google**
**fixed the root path**
https://eppo-group.slack.com/archives/C037Q5SPQET/p1682565684341709?thread_ts=1682565028.152469&cid=C037Q5SPQET
**problem - lukas reports thats the android sdk docs are showing up as netlify**
https://eppo-group.slack.com/archives/C02P01LSEE8/p1684517678910889
**changes**
The existing redirect rules only handle the top level URL.
* `https://adoring-yonath-6ecb9d.netlify.app` redirects and thus is removed from google’s index
* `https://adoring-yonath-6ecb9d.netlify.app/feature-flags/sdks/server-sdks/` (or any param/query string) does not
Expanding the redirect rules to handle all urls.
**reference**
https://docs.netlify.com/routing/redirects/redirect-options/#splats
=> Update _redirects to handle all URLs from showing netlify

docs/feature-flags/sdks/client-sdks/android.md
**customer feedback**
**why?**
using the builder pattern, when `buildAndInit` is called it assumes that `application` is not null
=> android: add instructions to set application(application) before buildAndInit

docusaurus.config.js
Chas and I are working to get access to https://docsearch.algolia.com/ but its taking a bit of time; we want to disable the algolia search for now so that customers don't see a bad state.
=> disable algolia docsearch

docs/data-management/definitions/assignment-sql.md
A few minor edits to the Assignment SQL page. This is just to fix confusion around how Assignment SQLs fit in for E2E customers.
I would like to do another pass on all of the definitions pages and replace screenshots with new UI, tidy things up, etc. This PR is just to get some rather misleading things fixed
=> light pass on assignment SQLs doc

docs/statistics/confidence-intervals/statistical-nitty-gritty.md
Currently, we are showing the sample variance instead of the variance of the estimator incorrectly in a few places. I cleaned this up.
Also I updated the docs to reflect our change to the default prior.
=> [fix] Solve issues with sample variance vs variance of estimator

docs/feature-flags/sdks/index.md
Previously said 10 minutes to update, which should be out of date
=> updated latency on SDK page

docusaurus.config.js
Currently, the footer of the Docs site points to "https://geteppo.com", which 301 redirects to "https://www.geteppo.com" - updated to point directly to the canonical version of the URL for SEO purposes
=> Update docusaurus.config.js - correct footer links to marketing site

docs/feature-flags/sdks/node.md, docs/how-tos/event-logging.md
The Segment Analytics Node.js library used in these files was deprecated in early 2023. I have updated the import and instantiation to align with the latest library. 
These changes are based on the official Segment [migration guide](https://segment.com/docs/connections/sources/catalog/libraries/server/node/migration/).
I have also tested this code in an ongoing project with Eppo and it works as expected. 
Please let me know if you have any questions.
=> Updated to latest Segment Node.js library

docs/data-management/metrics/simple-metric.md, docs/statistics/confidence-intervals/statistical-nitty-gritty.md
- Updated the description of retention metrics to reflect the changes from [EXP-916](https://linear.app/eppo/issue/EXP-916/[farmers-dog]-improve-retention-and-conversion-metric-calculation) ([Slack context](https://eppo-group.slack.com/archives/C01TTTNMCBB/p1704299072796209))
While I was at it, also
- Updated Bayesian default prior standard deviation, and added instruction on how to change it
- Fixed a few typos in statistical nitty-gritty
=> Retention metric definition and Bayesian defaults

docs/how-tos/connecting-dwh/bigquery.md, docs/quick-starts/feature-flag-quickstart.md
I am suggesting the following minor improvements. Please feel free to disagree.
1. In the instructions for setting up BigQuery, the _eppo_output_ dataset is created in step 1 and referenced as such in step 2 so it makes sense to reference it as such in step 3. 
2. Per [this comment](https://github.com/Eppo-exp/js-client-sdk-common/blob/0898d84072fb22a67ff659be15c2f44e84ea61c6/src/client/eppo-client.ts#L110) in the JS SDK, the _getAssignment_ function has been deprecated so I have replaced it with _getStringAssignment_. We could though instead use  _get < Type > Assignment_ and add a note to explain 'Type' further.
=> Minor suggestions

docs/statistics/sample-ratio-mismatch.md
The choice of alpha may be surprising. Added an explainer on why it's appropriate for SRM tests (expanding on the existing note about sequential testing).
=> Add info box on why alpha=0.001 for SRM tests

docs/feature-flags/sdks/javascript.md, docs/feature-flags/sdks/node.md
🎟️ **Ticket:** [FF-1486 - Update Node and JS Client Docs for new polling options](Update Node and JS Client Docs for new polling options)
The recently released Node JS ([PR](https://github.com/Eppo-exp/node-server-sdk/pull/45)) and Client JS ([PR](https://github.com/Eppo-exp/js-client-sdk/pull/45)) SDKs expose additional optional initialization options for configuring how experiment configurations should be requested. These docs document these.
---
---
Note that the two are the same, except for the Client JS has a `pollAfterSuccessfulInitialization` option that defaults to `false`, whereas its always `true` for node and not an option.
=> Add documentation for new Node and Client JS Initialization Options

docs/sdks/server-sdks/python.md
A more straightforward write-up of getting the Python SDK running, splitting the advanced configuration into a separate section.
More work is needed to give code examples for advanced set-up.
=> Simpler Get Started Python example

docs/data-management/index.md, docs/feature-flagging/experiment-assignment.md
A few minor fixes while I was reading through the feature flags documentation (+ one more I caught by searching)
=> Fix typos in feature flagging section

docs/experiment-analysis/segments.md
I noticed those delimiters were broken when going through the docs.
=> Minor: Fixing delimiters for Notes

docs/guides/non-inferiority-tests.md
We have a line where we call `\alpha` the "confidence level" rather than the "significance level." This confused me at first because typically the "confidence level" refers to `1 - \alpha`.  For example, a confidence level of 95% corresponds to `\alpha`=0.05. See terminology in https://en.wikipedia.org/wiki/Statistical_significance
=> Changed confidence level to significance level

docs/guides/anonymous-explainer.md
It looks like the final result of the query (which I believe is the mapping query) is missing `user_id`
=> Added user_id to query

.gitignore, docs/sdks/sdk-features/bandits.md, docs/sdks/server-sdks/java.md
🎟️  **Ticket:** [FF-1777 - Update documentation for bandits](https://linear.app/eppo/issue/FF-1777/update-documentation-for-bandits)
Here we add in the documentation about interacting with bandits to the Java Server SDK.
I also added a higher-level bandits section in the SDK Features section. Note it uses Java examples (many from the Java Server SDK documentation), as this is the only SDK we have right now.
=> Add Bandit Documentation

docs/guides/analyzing-clustered-experiments.md, docs/guides/running-clustered-experiments.md
Added a draft of a new guide that outlines running clustered experiments.
I'm making this a draft for now because I think we need to clarify what Eppo _can_ and _can't_ accommodate with its current functionality. I think the main limitations are with regard to entry points. I.e. we randomize by company, but we only want to include users in the experiment after they have performed action X.
=> Added guide on running clustered experiments

docs/sdks/client-sdks/index.md, docs/sdks/server-sdks/index.md
I noticed some strange behavior in our docs. If you navigate directly to the Server SDK page (i.e. click on this [link](https://docs.geteppo.com/sdks/server-sdks)), and then scroll down and click on one of the languages, it routes you to a broken link (e.g. https://docs.geteppo.com/sdks/python). 
However, if you navigate to the same page by clicking "Server SDKs" in the sidebar, it works as expected. I suspect this is due to quirks with relative paths. I changed the references to absolute paths in this PR and that seems to fix the issue.
Ditto for Client SDKs.
=> Fix broken links in SDK documentation

docs/sdks/client-sdks/react-native.md
The docs for React Native were prematurely updated. The [SDK](https://github.com/Eppo-exp/react-native-sdk) hasn't yet been updated to v3. This PR reverts the change to the docs to make sure that the docs and the latest version of the SDK are matched.
=> Revert changes to react-native to pre-v3 state

docs/sdks/client-sdks/react-native.md
Reverts Eppo-exp/eppo-docs#359 now that [v3](https://github.com/Eppo-exp/react-native-sdk/releases/tag/v3.0.0) has been released
=> Revert "Revert changes to react-native to pre-v3 state"

docs/sdks/client-sdks/android.md
Update the Android documentation for UFC:
* New assignment method signatures (e.g., flag key first, default value)
* Describe the additional `extraLogging` and `metaData` assignment fields
* Remove section on handling `null`
I also expanded on some of the existing examples:
* Include initialization callback when initializing the SDK
* Include the subject key when logging an assignment
=> Update Android documentation for UFC

docs/statistics/sample-ratio-mismatch.md
Noticed that we don't explain how we address multiple comparisons in the dimensional SRM checks, so I added a brief explanation.
=> Added multiple comparisions explanation for dimensional SRM checks

docs/data-management/metrics/simple-metric.md
We noticed that many users are choosing COUNT DISTINCT when COUNT would give similar results. This PR adds an info box about the higher warehouse costs and gives a more fleshed out example on how to choose between the two.
=> Add tip on choosing between COUNT DISTINCT and COUNT

docs/sdks/server-sdks/java.md, docs/sdks/server-sdks/php.md, docusaurus.config.js
Looked through the languages used and added them to the list of additional languages.
Some were already covered by default Docusaurus configuration but I decided to be explicit and add all used languages (in case default configuration changes in the future).
=> feat: enable highlighting for more languages

docs/statistics/multiple-testing.md
- Make it more explicit that we do multiple testing correction also across _variants_, and add tip on disabling unused variants
- Add details and reference on why Bayesian does not have MTC
=> Add tip on disabling unused variants + reference for Bayesian

docs/sdks/server-sdks/ruby.md
Bundler with Gemfile is the most common way to consume gems in the ruby world
=> chore(ruby): Add `Gemfile` instructions for using SDK

docs/sdks/sdk-features/debugging-flag-assignment.md
These changes reflect the updates in https://github.com/Eppo-exp/js-client-sdk-common/pull/113. @aarsilv and I talked through changing the return value structure from `value` to `variation`, and also including `action` so that the return structure is consistent across assignment/bandit SDK functions. This consistency will be helpful for languages with type systems that are less flexible than TypeScript, will make it easier for customers to learn, and will provide avenues for future proofing in the case that we consolidate functionality.
=> "Evaluation Details" documentation updates

docs/sdks/server-sdks/java.md, docs/sdks/server-sdks/node.md
Adds bandit documentation for the Node SDK.
This was is heavily inspired by the [Python](https://github.com/Eppo-exp/eppo-docs/blob/main/docs/sdks/server-sdks/python.md#6-contextual-bandits) and [Java](https://github.com/Eppo-exp/eppo-docs/blob/main/docs/sdks/server-sdks/java.md#usage-with-contextual-multi-armed-bandits) documentation.
=> Add documentation for bandits with the Node SDK

docs/quick-starts/bandit-quickstart.md, docs/sdks/sdk-features/bandits.md
A couple of quick fixes to address user feedback:
* Add reference to `getBanditAction` - but maybe we should rework this section entirely, and remove all reference to the (now outdated?) overloaded usage of getStringAssignment
* Refer to best practices on event logging more consistently
* Remove reference to logging non-bandit assignments, which we decided to not support across SDKs because of limited value
For future work:
* port all of the code examples to the most commonly used SDK - either Node or Python
* consolidate: right now a lot of content is duplicative between sections, which makes it harder to keep things in sync. Instead of duplicating, we should make each page distinct, possibly cutting down the number, and cross-reference more among those that remain
=> Quick fixes in bandit quickstart and SDK features page

docusaurus.config.js
This PR updates the RunLLM widget configuration to use our new widget.runllm.com domain. 
This enables us to have better control over caching and ensures that you are always getting the latest version of our widget. 
We've also updated the version tag so that it's no longer required, so you can omit the version parameter here.
Let me know if you have any questions here, happy to help.
Our docs here have been updated to reflect these changes:
https://docs.runllm.com/chat-widget
=> RunLLM Widget Configuration Update

docs/sdks/client-sdks/android.md
Instead of specific version. All changes on `3.x.x` will be non-breaking.
=> Android SDK installation instructions point to 3.+

docs/sdks/server-sdks/go.md
Updating for the latest release:
* changes order of `flag` and `subject` parameters
* `InitClient` returns an `err`
This doc page needs a bunch more work but I want to quickly get it correct.
=> golang v5 updates

docs/experiment-analysis/index.md
Winsorization doesn't remove outliers, so this note is a little confusing. "Cap outliers" is more precise.
=> Updated description of winsorization in experiment analysis note

docs/sdks/server-sdks/java.md, docs/sdks/server-sdks/node.md
Update the Java SDK Documentation to account for its migration to UFC and for bringing its Bandit methodology up to speed with all the changes that happened since this first implementation.
=> Update Java SDK Documentation

docs/administration/okta.md
Some customers are assuming that we support IdP-initiated logins via an Okta tile. This warning plus copy change should help.
I would prefer `warning`, but that renders a `danger`, so I used `info` instead.
=> update okta page with info block about IdP-initiated logins

docs/sdks/server-sdks/python.md
https://linear.app/eppo/issue/FF-3150/%5Bpython%5D-allow-python-sdk-to-be-bootstrapped-from-configuration
Implementation: https://github.com/Eppo-exp/python-sdk/pull/70
=> FF-3150 Documentation for manual configuration control

docs/statistics/cuped.md
[I checked that our Cuped Lookback queries were covering 30 days prior to the assignment event](https://eppo-group.slack.com/archives/C058QMZ6XQC/p1725348358750229).
=> Clarifying Cuped reference point

docs/contextual-bandits/deployment.md
A [client wanted](https://eppo-group.slack.com/archives/C05R6BK5BB9/p1725961841239789) to run a Bandit on a limited audience (15%). They asked how to allocated their traffic.
We have internal documents explaining that we should split, customer-facing documents that explain both, but not that this separation is necessary.
=> Specify that Bandit has to be split between training and testing.

src/css/custom.css
Quick fixes to update docs styling:
- Loaded Cofo sans & Cofo mono
- Fixed heading sizes according to design
- Changed background colors a bit to create separation for left sidebar
=> Change docs fonts & background colors

docs/sdks/sdk-features/bandits.md
The `[!TIP]` looked odd on screen.
=> Small formating nit on Bandit page.

src/css/custom.css
- Added brand colors as  --ifm color variables
- Swapped them to the left nav & toc color background. Made bg use gray-300 because it needs a bit more contrast
- Fixed padding where the hover was touching the right side of sidebar
- Added left nav border back to create separation between nav and content in dark mode
- Changed footer background color to match brand color
- Added a bit more space to horizontal padding for main content area
=> Color & spacing polish

docs/contextual-bandits/actions_contexts.md, docs/sdks/sdk-features/bandits.md, docs/sdks/server-sdks/java.md, docs/sdks/server-sdks/node.md, docs/sdks/server-sdks/python/index.md
Fixing based on this conversation:
=> Update bandit action context examples to use attributes only related to subject-action interaction

misc/code_snippets.md
Hang asked for feedback on the new Feature Flags landing page ([slack thread](https://eppo-group.slack.com/archives/C07PHSG19A4/p1729720909264639)).
Currently our code snippets are sorta all over the place. I typed up some examples using ai, docs, and git repos, with the intention of having "the same call" for every SDK. I feel this gives a better developer experience when previewing the different languages.
Use the rich diff to see the actual Markdown.
=> Proposal for consistent code snippets on feature flags landing page.

docs/sdks/server-sdks/ruby.md
Updating Ruby docs to reflect new usage pattern, specifically the arguments to `get_string_assignment`
Based on Slack thread [here](https://eppo-group.slack.com/archives/C058QMZ6XQC/p1730314066963259?thread_ts=1730313832.581419&cid=C058QMZ6XQC)
I feel pretty confident this is right based on [this](https://github.com/Eppo-exp/rust-sdk/blob/6013f7ab8a0b49db03417124bedaae63aa34550e/ruby-sdk/lib/eppo_client/client.rb#L46), the only piece that I'd want to confirm is the part about debugging as I don't see anything about that in the code (maybe it's a Ruby thing though)
=> Update get assignment arguments in Ruby docs

docs/sdks/server-sdks/python/index.md, docs/sdks/server-sdks/ruby.md
This PR adds the changes proposed [here](https://github.com/Eppo-exp/eppo-docs/pull/432), but puts them in the IA layout we've been shifting SDK docs to.
There were a few unresolved threads in the original PR that were beyond my understanding of our current state of bandits on Ruby
=> updated ruby layout, added bandits

docs/sdks/client-sdks/android.md, docs/sdks/client-sdks/ios.md, docs/sdks/client-sdks/javascript.md, docs/sdks/client-sdks/react-native.md, docs/sdks/faqs/common-issues.md, docs/sdks/server-sdks/go.md, docs/sdks/server-sdks/java.md, docs/sdks/server-sdks/node.md, docs/sdks/server-sdks/php.md, docs/sdks/server-sdks/ruby.md, docs/sdks/server-sdks/rust.md
Per gap identified by @chasdevs.
Adding explicit information around when flags become available relative to initialization.
=> Adding init flag availability info to SDKs

src/components/ApiOptionRef.js, src/css/custom.css
Adding a component to template API reference tables.
Markdown tables leave a lot to be desired for maintainability and authoring. Additionally, the HMTL tables they output have display issues on diminished viewports and also have some issues with inconsistent column sizing.
This component fixes both of those issues. First, the syntax doesn't require putting entire rows into single lines. Second, component lets you pass markdown and react components as part of its inner element for the description. Lastly, it templates out into a responsively designed set of divs.
```markdown
<ApiOptionRef name="Markup Test" defaultValue="5000">
Markdown syntax test
Lorem Ipsum
*italics*
**bold**
[link](https://www.google.com)
Table:
| Header 1 | Header 2 | Header 3 |
| -------- | -------- | -------- |
| …
```
=> Adding API Option Reference Component

docs/data-management/certified-metrics/eppo-schema.md
We currently don't specify that reference_url should start with http:// or https://
That led to some confusion for one of our customer.
=> Fix reference_url string

docs/sdks/preforking.md, docs/sdks/server-sdks/python/index.md, docs/sdks/server-sdks/ruby/initialization.mdx
Add documentation for using Python/Ruby SDKs with pre-forking web servers
=> docs(ruby,python): add documentation for pre-forking servers

docs/data-management/definitions/fact-sql.md, docs/sdks/index.md, docs/sdks/server-sdks/index.md, docs/sdks/server-sdks/python/_category.json, docs/sdks/server-sdks/python/_category_.json, docs/sdks/server-sdks/python/announcing-python-4-0.md, docs/sdks/server-sdks/python/assignments.mdx, docs/sdks/server-sdks/python/bandits.mdx, docs/sdks/server-sdks/python/examples.mdx, docs/sdks/server-sdks/python/initialization.mdx, docs/sdks/server-sdks/python/intro.mdx, docs/sdks/server-sdks/python/quickstart.mdx, static/_redirects
Updating the Python docs to follow the same multipage pattern as our Javascript docs.
- The goal is to make the learning journey for engineers working with specific SDKs easier.
- Content is easier to find in the TOC, improving navigability.
- Code samples for typed assignment examples have been added for ease of use.
- Boilerplate prose docs have been added to allow engineers to learn about relevant conceptual information alongside the code without having to context switch to other parts of the docs.
- Let's discuss the Python SDK 4.0 announcement doc. Are there any places in the docs where the differences between 3.0 and 4.0 are different enough that we need to preserve older doc information? Are we safe to get rid of that page?
- Please make sure the code samples are accurate.
=> Adding Python docs to new template update

docs/sdks/server-sdks/python/initialization.mdx, docs/sdks/server-sdks/python/quickstart.mdx
The SDK will throw an error if `assignment_logger` is not specified in `ClientConfig`. This updates the quickstart and initialization pages to account for this.
I also made the imports more explicit for the experiment and bandit sections of the quickstart, in case the reader skipped over the flagging section
=> added assignment logger as an input for ClientConfig

docs/experiment-analysis/holdouts.md
🎟️ **Ticket:** [FF-3808](https://linear.app/eppo/issue/FF-3808/)
🗨️ **Slack Convo:** ["... getting the assignment data is key..."](https://eppo-group.slack.com/archives/C030T4F1NFN/p1737135810104969?thread_ts=1736856747.908079&cid=C030T4F1NFN)
The existing holdout documentation was confusing in some places, particularly with regard to how holdouts are handled in assignment logging.
This PR gives it a once-over to address this confusion.
We've also updated it to reflect some recently made UX changes, such as treating the default variation as the status quo.
👀 👉 **Direct preview link:** [Core Concepts - Experiment Analysis - Holdouts](https://deploy-preview-575--eppo-data-docs.netlify.app/experiment-analysis/holdouts/)
=> Update holdouts documentation

docs/sdks/client-sdks/javascript/react.mdx
We have dedicated Next.js docs, but I figure this is easy enough to get tripped up on that it's worth adding a callout
=> Added note about "use client" to React docs

docusaurus.config.js
Updated Google Analytics Measurement ID to match Marketing Site to share cross-domain data
=> Updated Google Analytics Measurement ID

docs/quick-starts/bandit-quickstart.md
As [mentioned by @gregdale in Slack](https://eppo-group.slack.com/archives/C058QMZ6XQC/p1742165369958639)
=> Fix link from bandit-quickstart.md to Python Bandits

docs/reference/webhook.mdx
* expanding web-hook events to send when a flag configuration changes
* improve docs
* Add section on new `flag configuration updated` web-hook
* generalize the page away from explicitly experiment centric events
* add integration and signature verification section
=> add flagging webhook and integration instructions (FF-4159)

docs/sdks/server-sdks/go/assignments.mdx, docs/sdks/server-sdks/go/initialization.mdx, docs/sdks/server-sdks/go/quickstart.mdx
As pointed out by a client:
https://eppo-group.slack.com/archives/C06GC8Z4EDS/p1742545731988389
=> Typo in SDK’s address in in Golang Quickstart

docs/reference/webhook.mdx
[Link to linear](https://linear.app/eppo/issue/FF-4298/webhook-signature-verification-instructions)
Clarifications/corrections:
* Unclear what "payload" means: the entire event-data-signature object? But how could we possibly generate a signature if the payload already has a signature in it? It would be less confusing if we specify to use the "data" object in the request body.
* JSON data types must not be pre-coerced into strings before running through the signature matching algorithm. This was a subtle gotcha that it would be preferable to avoid in the future.
=> Webhook signature verification instructions

docs/sdks/developer-tools-extension.md
Add missing `enableOverrides` parameter to Eppo Developer Tools documentation
=> fix docs to enable overrides

docs/sdks/client-sdks/javascript/gdpr-compliance.mdx, docs/sdks/client-sdks/javascript/troubleshooting.mdx
_Eppo Internal:_
🎟️ **Ticket:** [FF-4336 - Update JS Client SDK Docs for GDPR Compliance Approach](https://linear.app/eppo/issue/FF-4336/update-js-client-sdk-docs-for-gdpr-compliance-approach)
In certain situations, such as GDPR Compliance, one may want to buffer assignment events and send them at a later time.
Eppo's JavaScript Client SDK can handle this, and this documentation update includes instructions on how.
👀  [Direct link in deploy preview](https://deploy-preview-666--eppo-data-docs.netlify.app/sdks/client-sdks/javascript/gdpr-compliance/)
=> Add instructions on delaying sending assignments until a later time

docs/quick-starts/bandit-quickstart.md
Clarify that the unique bandit identifier should be `bandit_key` in the db table, rather than the more confusing `key`
=> [bandits] For clarity, use bandit_key as column name

docs/sdks/client-sdks/ios/assignments.mdx, docs/sdks/client-sdks/ios/quickstart.mdx
Remove try keyword from `getStringAssignment`, `getBooleanAssignment`, `getIntegerAssignment`, `getNumericAssignment`, and `getJSONStringAssignment` method calls since these methods no longer throw exceptions.
=> docs: update iOS SDK docs for non-throwing assignment methods

docs/sdks/server-sdks/dotnet/initialization.mdx
See https://github.com/Eppo-exp/dot-net-server-sdk/pull/63
=> docs: add RequestTimeoutMillis option to .NET SDK initialization docs
